#include <stdio.h>
#include "unitconv.h"
#include "calc.h"
#include "unitdata.h"

int conv_length(double val, char *unitname, unsigned int chainflag)
{
	int i, ret; double cnvval;
	unit unitlist[] = {
		/* Metric */
		{"fm", 1e-15, 0, {"femtometer","femtometre","fermi",""}},
		{"pm", 1e-12, 0, {"picometer","picometre","stigma","bicron",""}},
		{"nm", 1e-9, 0, {"nanometer","nanometre",""}},
		{"um", 1e-6, 0, {"micrometer","micrometre","micron",""}},
		{"mm", 1e-3, 0, {"millimeter","millimetre",""}},
		{"cm", 1e-2, 0, {"centimeter","centimetre",""}},
		{"dm", 1e-1, 0, {"decimeter","decimetre",""}},
		{"m", 1e0, 0, {"meter","metre",""}},
		{"km", 1e3, 0, {"kilometer","kilometre",""}},
		{"Mm", 1e6, 0, {"megameter","megametre",""}},
		{"Gm", 1e9, 0, {"gigameter","gigametre",""}},
		{"Tm", 1e12, 0, {"terameter","terametre","spat",""}},
		/* Atomic unit */
		{"a_0", BOHR_RADIUS, 0, {"bohr","bohrradius","bohr radius","Bohr radius","au","au(length)","aulength","atomiclength","atomicunitlength","atomicunitoflength","atomic unit of length",""}},
		/* Planck unit */
		{"l_p", sqrt(H_BAR * GRAVCONST / LIGHTSPEED / LIGHTSPEED / LIGHTSPEED), 0, {"plancklength","planck length","Planck length",""}},
		/* Miscellaneous */
		{"angstrom", 1e-10, 0, {""}},
		{"pc", 3.08567782e16, 0, {"parsec",""}},
		{"AU", 1.49597870691e11, 0, {"astronomicalunit","astronomical unit",""}},
		{"l.ns.", LIGHTSECOND_TO_METRE / 1e9, 0, {"light-nanosecond","lightnanosecond",""}},
		{"l.us.", LIGHTSECOND_TO_METRE / 1e6, 0, {"light-microsecond","lightmicrosecond",""}},
		{"l.ms.", LIGHTSECOND_TO_METRE / 1e3, 0, {"light-millisecond","lightmillisecond",""}},
		{"l.s.", LIGHTSECOND_TO_METRE, 0, {"light-second","lightsecond",""}},
		{"l.m.", LIGHTSECOND_TO_METRE * MINUTE_TO_SECOND, 0, {"light-minute","lightminute",""}},
		{"l.h.", LIGHTSECOND_TO_METRE * HOUR_TO_SECOND, 0, {"light-hour","lighthour",""}},
		{"l.d.", LIGHTSECOND_TO_METRE * DAY_TO_SECOND, 0, {"light-day","lightday",""}},
		{"l.y.", LIGHTSECOND_TO_METRE * YEAR_TO_SECOND, 0, {"ly","light-year","lightyear",""}},
		{"cable", NAUTICAL_MILE_TO_METRE/10, 0, {""}},
		{"NM", NAUTICAL_MILE_TO_METRE, 0, {"nmi","nauticalmile","nautical mile",""}},
		{"NL", NAUTICAL_MILE_TO_METRE*3, 0, {"nl","nauticalleague","nautical league",""}},
		{"lieue", 4000, 0, {""}},
		/* US Customary-Imperial */
		{"mil", INCH_TO_METRE / 1e3, 0, {"thou",""}},
		{"ln", FOOT_TO_METRE / 144, 0, {"line",""}},
		{"barleycorn", FOOT_TO_METRE / 36, 0, {""}},
		{"finger", INCH_TO_METRE * .875, 0, {""}},
		{"in", INCH_TO_METRE, 0, {"inch",""}},
		{"stick", FOOT_TO_METRE / 6, 0, {""}},
		{"palm", FOOT_TO_METRE / 4, 0, {""}},
		{"hand", FOOT_TO_METRE / 3, 0, {""}},
		{"finger(cloth)", INCH_TO_METRE * 4.5, 0, {""}},
		{"span", FOOT_TO_METRE / 2, 0, {""}},
		{"lnk", CHAIN_TO_METRE / 100, 0, {"link",""}},
		{"span", INCH_TO_METRE * 9, 0, {"",""}},
		{"ft", FOOT_TO_METRE, 0, {"foot","lnk(Ramsden)","link(Ramsden)",""}},
		{"cubit", FOOT_TO_METRE * 1.5, 0, {""}},
		{"pace", FOOT_TO_METRE * 2.5, 0, {""}},
		{"yd", FOOT_TO_METRE * 3, 0, {"yard",""}},
		{"ell", FOOT_TO_METRE * 3.75, 0, {""}},
		{"fm", FOOT_TO_METRE * 6, 0, {"fathom",""}},
		{"rd", FOOT_TO_METRE * 16.5, 0, {"rod","pole","perch",""}},
		{"rope", FOOT_TO_METRE * 20, 0, {""}},
		{"ch", CHAIN_TO_METRE, 0, {"chain",""}},
		{"ch(Ramsden)", FOOT_TO_METRE * 100, 0, {"chain(Ramsden)",""}},
		{"cable(UK)", FOOT_TO_METRE * 608, 0, {"cable(imperial)",""}},
		{"fur", CHAIN_TO_METRE * 10, 0, {"furlong",""}},
		{"cable(US)", FOOT_TO_METRE * 720, 0, {""}},
		{"mi", MILE_TO_METRE, 0, {"mile",""}},
		{"mi(tactical)", FOOT_TO_METRE * 6000, 0, {"mile(tactical)","tacticalmile","tactical mile",""}},
		{"NM(Adm)", FOOT_TO_METRE * 6080, 0, {"nmi(Adm)",""}},
		{"mi(geographical)", FOOT_TO_METRE * 6082, 0, {"mi(Geo)","mi(geo)","mile(Geo)","mile(geo)","mile(geographical)","geographicalmile","geographical mile",""}},
		{"mi(telegraph)", FOOT_TO_METRE * 6087, 0, {"mile(telegraph)","telegraphmile","telegraph mile",""}},
		{"lea", MILE_TO_METRE * 3, 0, {"league",""}},
		{"ft(US)", SURVEY_FOOT_TO_METRE, 0, {"foot(US)",""}},
		{"ch(US)", SURVEY_FOOT_TO_METRE * 66, 0, {"chain(US)",""}},
		{"mi(US)", SURVEY_FOOT_TO_METRE * 5280, 0, {"mile(US)",""}},
		{"ft(Ben)", 3.04799735e-1, 0, {"foot(Ben)",""}},
		{"ft(Cla)", 3.047972654e-1, 0, {"foot(Cla)",""}},
		{"ft(Ind)", 3.04799514e-1, 0, {"foot(Ind)",""}},
		{"ft(Sear)", 3.0479947e-1, 0, {"foot(Sear)",""}},
		/* Chinese */
		{"hu1", CHINESE_FOOT_TO_METRE / 1e5, 0, {"hu",""}},
		{"si1", CHINESE_FOOT_TO_METRE / 1e4, 0, {"si",""}},
		{"hao2", CHINESE_FOOT_TO_METRE / 1e3, 0, {"hao",""}},
		{"li2", CHINESE_FOOT_TO_METRE / 100, 0, {"li",""}},
		{"fen1", CHINESE_FOOT_TO_METRE / 10, 0, {"fen","chineseinch","Chinese inch","chinese inch",""}},
		{"chi1", CHINESE_FOOT_TO_METRE, 0, {"chi","chinesefoot","Chinese foot","chinese foot",""}},
		{"bu4", CHINESE_FOOT_TO_METRE * 5, 0, {"bu","chinesepace","Chinese pace","chinese pace",""}},
		{"zhang4", CHINESE_FOOT_TO_METRE * 10, 0, {"zhang",""}},
		{"yin3", CHINESE_FOOT_TO_METRE * 100, 0, {"yin",""}},
		{"li3", 500, 0, {"li",""}},
		/* Hong Kong */
		{"fen(HK)", HK_FOOT_TO_METRE / 100, 0, {"fen",""}},
		{"tsun", HK_FOOT_TO_METRE / 10, 0, {"hongkonginch","hkinch","HKinch","hk inch","HK inch","Hong Kong inch",""}},
		{"chek", HK_FOOT_TO_METRE, 0, {"hongkongfoot","hkfoot","HKfoot","hk foot","HK foot","Hong Kong foot",""}},
		/* Japanese-Taiwanese */
		{"moh", JAPANESE_FOOT_TO_METRE / 100, 0, {"mou","mo",""}},
		{"rin", JAPANESE_FOOT_TO_METRE / 100, 0, {""}},
		{"bu(JP)", JAPANESE_FOOT_TO_METRE / 100, 0, {"bu",""}},
		{"sun", JAPANESE_FOOT_TO_METRE / 10, 0, {"japaneseinch","japanese inch","Japanese inch",""}},
		{"shaku", JAPANESE_FOOT_TO_METRE, 0, {"japanesefoot","japanese foot","Japanese foot","kanejaku",""}},
		{"ken", JAPANESE_FOOT_TO_METRE * 6, 0, {"hiro","edoma","japanesefathom","japanese fathom","Japanese fathom",""}},
		{"ken(Kyoto)", JAPANESE_FOOT_TO_METRE * 6.5, 0, {"kyoma","kyouma","kyohma",""}},
		{"joh", JAPANESE_FOOT_TO_METRE * 10, 0, {"jo","jou",""}},
		{"choh", JAPANESE_FOOT_TO_METRE * 360, 0, {"cho","chou",""}},
		{"ri", JAPANESE_FOOT_TO_METRE * 36 * 360, 0, {""}},
		{"sun(kujirajaku)", 2.5/66.0, 0, {""}},
		{"shaku(kujirajaku)", 25.0/66.0, 0, {"kujirajaku",""}},
		/* Special */
		{"pt(US)", INCH_TO_METRE / 72.272, 0, {"point(US)",""}},
		{"pt(Didot)", 5e-2 / 133.0, 0, {"point(Didot)",""}},
		{"pt(ps)", INCH_TO_METRE / 72, 0, {"pt(postscript)","pt(PostScript)","point(ps)","point(postscript)","point(PostScript)",""}},
		{"pt(TeX)", INCH_TO_METRE / 72.27, 0, {"point(TeX)",""}},
		{"pica(US)", FOOT_TO_METRE / 72.272, 0, {""}},
		{"pica(Didot)", 5e-2 / 133.0 * 12, 0, {""}},
		{"pica(ps)", FOOT_TO_METRE / 72, 0, {"pica(postscript)","pica(PostScript)",""}},
		{"pica(TeX)", FOOT_TO_METRE / 72.27, 0, {""}},
		{"twp", INCH_TO_METRE / 1440, 0, {"twip",""}},
		{"xu", 1.0021e-13, 0, {"xunit","x unit","siegbahn",""}},
	};
	unsigned int listlen = (sizeof(unitlist) / sizeof(unit));
	
	ret = calculate(val, unitname, listlen, unitlist, chainflag, "length", &cnvval);
	return ret;
}
